### ISSUE TITLE
Include IPFS Cluster as top level project

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/camp.ipfs.io#16]
Hi, IPFS Cluster is missing from the logos:

![image](https://user-images.githubusercontent.com/1027022/57586771-e2f71380-74fa-11e9-9e82-6a3f138499ce.png)

and also at the bottom there should be a link to https://cluster.ipfs.io in the "Related Projects" area.

@cwaring can you help here?

**Comment by cwaring** [comment]
No problem, I'll make sure it's added in the next release👌
