### ISSUE TITLE
scrollTop not set to 0 when change page on Firefox

### ISSUE THREAD

**Issue by alanshaw** [ipfs/camp.ipfs.io#17]
1. Open Firefox
1. Navigate to camp.ipfs.io
1. Scroll to bottom of page
1. Click on FAQ link in footer
1. Nothing happens

**Comment by cwaring** [comment]
Good catch, it seems to works intermittently so I'll double check the component in the latest dev build.

**Comment by cwaring** [comment]
I've deployed a patch, would you mind checking again now? Thanks

**Comment by alanshaw** [comment]
It good now thanks
