### ISSUE TITLE
Scroll performance

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/camp.ipfs.io#5]
On FF66 (but probably on previous too) the scroll performance in the upper part of the website is very bad.

**Comment by cwaring** [comment]
Thanks for reporting, can you give me a little more info about the machine and OS you are running on and I'll look into getting it patched up.

**Comment by Kubuxu** [comment]
System Arch Linux, machine i5-4200m, 16GB RAM, SSD.

The performance is ok after enabling this `display: none`.
<div class="stars" style="/*! display: none; */"></div>

**Comment by Kubuxu** [comment]
It might be a new problem in FF66 or just my notebook being old.
